### ISSUE TITLE
Algorithm for deciding which Campaign to call

### ISSUE THREAD

**Issue by jonaraphael** [magicseth/onecall#11]
Factors that could be important:
• Campaigns' callobjective
• Total number of calls already placed for each campaign
• User preference of subjects (future)
• etc...

**Comment by magicseth** [comment]
random coild be fine too.

**Comment by jonaraphael** [comment]
random from all campaigns that have a callable target, weighted according to their CALLOBJECTIVE
e.g. A.callobj = 1000 and B.callobj=100, will return A ten times as frequently as B.
e21d18
