### ISSUE TITLE
don't log uncompleted calls as real calls

### ISSUE THREAD

**Issue by magicseth** [magicseth/onecall#26]

**Comment by magicseth** [comment]
I have almost all the hooks in place now. 

Jona there is a place in def logCallEnd():
that you can update the call row with a status, and a duration, and a recordingURL so we can see how long, was it successful and listen to it.

**Comment by jonaraphael** [comment]
Done 5635d5
We need to know what the possible Statuses are, so that we can no how to filter for failed calls.

**Comment by jonaraphael** [comment]
done 19bbd5
