### ISSUE TITLE
Why am I signed in? my username and password should no longer work

### ISSUE THREAD

**Issue by magicseth** [magicseth/onecall#32]
Are we trusting client's about logged in status?

**Comment by jonaraphael** [comment]
> flask sessions expire once you close the browser unless you have a permanent session.

I can set the flag to permanent (31 days), but I don't think that's necessary.
You are correct that your username and password should no longer work, but changing the values in the database would not change whether your browser still has a valid session key.
http://stackoverflow.com/questions/11783025/is-there-an-easy-way-to-make-sessions-timeout-in-flask

**Comment by jonaraphael** [comment]
Also, my thought is that once we are happy with the deployed version, that we can create usernames for you and I (with secret passwords) and then change the admin password so that it is no longer accessible to anyone.
